package abandon;

import lucene.CountriesIndexer;
import lucene.Country;
import org.apache.lucene.queryparser.classic.ParseException;
import abandon.rdbms.DbHandler;

import java.io.IOException;
import java.sql.SQLException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws SQLException, ClassNotFoundException, IOException, ParseException {
        System.out.println(new App().getGreeting());
        CountriesIndexer countriesIndexer = new CountriesIndexer();

        //countriesIndexer.search();
        //System.exit(0);

        countriesIndexer.open();

        DbHandler dbHandler = new DbHandler();
        dbHandler.open();

        dbHandler.executeSqlScript("SELECT * FROM countrylist", r -> {

            /*elasticClient.indexCountry(r.getInt("CountryID"),
                                       r.getString("CountryName"),
                                        r.getString("CountryCode"));
                                        */
            Country c = new Country(r.getString("CountryID"),
                    r.getString("CountryName"),
                    r.getString("CountryCode"));
            countriesIndexer.addCountryToIndex(c);
        });

        countriesIndexer.close();
        dbHandler.close();

    }
}
